
[functions.test-push]
enabled = true
verify_jwt = true
import_map = "./functions/test-push/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-push/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-push/*.html" ]
[functions]
# (other global function settings)

[functions.send-request]
verify_jwt = false
