export const mockEventData = [
  {
    id: 'event_1',
    title: 'Balinese Cooking Class',
    location: 'Ubud, Bali',
    description: 'Learn to cook traditional Balinese dishes with a local chef',
    cost: 120,
    duration: '4 hours',
    category: 'Cultural',
  },
  {
    id: 'event_2',
    title: 'Sunset Dinner Cruise',
    location: 'Bali',
    description: 'Romantic dinner cruise with stunning sunset views',
    cost: 180,
    duration: '3 hours',
    category: 'Romantic',
  },
  {
    id: 'event_3',
    title: 'Rice Terrace Trekking',
    location: 'Tegalalang, Bali',
    description: 'Guided trek through beautiful rice terraces',
    cost: 85,
    duration: '2 hours',
    category: 'Adventure',
  },
  {
    id: 'event_4',
    title: 'Spa & Wellness Treatment',
    location: 'Various locations',
    description: 'Traditional Balinese spa treatment',
    cost: 150,
    duration: '2 hours',
    category: 'Wellness',
  },
  {
    id: 'event_5',
    title: 'Temple Tour',
    location: 'Bali',
    description: 'Visit ancient temples with cultural guide',
    cost: 95,
    duration: '6 hours',
    category: 'Cultural',
  },
  {
    id: 'event_6',
    title: 'Waterfall Adventure',
    location: 'Bali',
    description: 'Hike to hidden waterfalls and natural pools',
    cost: 110,
    duration: '4 hours',
    category: 'Adventure',
  },
  {
    id: 'event_7',
    title: 'Beach Club Day Pass',
    location: 'Seminyak, Bali',
    description: 'Access to exclusive beach club with pool and bar',
    cost: 200,
    duration: 'Full day',
    category: 'Luxury',
  },
  {
    id: 'event_8',
    title: 'Traditional Dance Performance',
    location: 'Ubud Palace',
    description: 'Evening performance of traditional Balinese dance',
    cost: 75,
    duration: '2 hours',
    category: 'Cultural',
  },
  {
    id: 'event_9',
    title: 'Volcano Sunrise Trek',
    location: 'Mount Batur',
    description: 'Early morning trek to watch sunrise from volcano',
    cost: 140,
    duration: '8 hours',
    category: 'Adventure',
  },
  {
    id: 'event_10',
    title: 'Private Beach Dinner',
    location: 'Nusa Dua, Bali',
    description: 'Exclusive private dinner on the beach',
    cost: 350,
    duration: '3 hours',
    category: 'Luxury',
  },
]; 